version: "3.8",
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: FILL THIS DATA IN PRODUCTION
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - ./pgdata:/var/lib/postgresql/data